apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-frontend
spec:
 template:
   metadata:
     labels:
       tire: frontend
   spec:
     containers:
       - name: httpd-frontend
         image: httpd:2.4-alpine
 selector:
   matchLabels:
      tire: frontend
 replicas: 3