apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration
  labels:
    app: web-app
spec:
  containers:
   - name: nginx
     image: nginx
  tolerations:  ### here we need to provide the same values which we used for the taint on the node. So that this pod will be tolerent for that node.
    - key: "app"  ## The values provided here should be dobule quoteded
      operator: "=" ## equal is the default operator
      value: "web-app"
      effect: "NoExecute"

####There are two special cases:

      ###An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.

      ###An empty effect matches all effects with key key1.
