apiVersion: v1
kind: Pod
metadata:
   name: configmap-pod
spec:
  containers:
    - name: front-end
      image: nginx
      env:
        - name: configmap-pod
          valueFrom:
            configMapKeyRef:
              name: <configmapname>
              key: APP_COLOR

# we can also use envFrom instead of env
# -envFrom:
 #   - configMapRef:
 #       - name: <configmapname>
